### ISSUE TITLE
Error Response (get error codes output by COTOHA API)

### ISSUE THREAD

**Issue by ysato5654** [tanaken0515/cotoha-ruby#5]
Can current cotoha-ruby (v0.2.0 ) get error codes output by the COTOHA API correctly?

When accessing COTOHA API under reached the usage limit (developers only) condition, I got error message.

```rb
client_id = 'xxx'
client_secret = 'xxx'
text = 'xxx'

client = Cotoha::Client.new(client_id: client_id, client_secret: client_secret)
client.create_access_token

response = client.sentiment(sentence: text)
```

Here is error message.

```
/opt/local/lib/ruby2.5/gems/2.5.0/gems/cotoha-0.2.0/lib/cotoha/connection.rb:31:in `request': POST https://api.ce-cotoha.com/api/dev/nlp/v1/sentiment: 429 - {"result"=>{}, "message"=>"An error has occurred.", "status"=>99996} (Cotoha::ClientError)
```

In this case, `response` is empty.

I hope that `response` has data of `{"result"=>{}, "message"=>"An error has occurred.", "status"=>99996}`.
What do you think about this? otherwise, my sample code is not correct?

**Comment by tanaken0515** [comment]
Thanks for the report 👍

**Comment by tanaken0515** [comment]
@ysato5654 
I am not good at English, so I will add a Japanese translation.
> 英語が得意ではないので、日本語訳も添えて記載しますね。

Does your application need error details for application logic?
> ysato5654 さんのアプリケーションでは、アプリケーションロジックとして、エラーの詳細が必要なのでしょうか？

In `cotoha-ruby`, errors in API requests are managed by the [Cotoha::Error](https://github.com/tanaken0515/cotoha-ruby/blob/31a94aeb50160449cce3c6def2faf8ddbea7ac9e/lib/cotoha/error.rb) class, and if the status code of the HTTP response is 4xx ~ 5xx, an Exception is raised.
> `cotoha-ruby` では、APIリクエストの際のエラーは [Cotoha::Error](https://github.com/tanaken0515/cotoha-ruby/blob/31a94aeb50160449cce3c6def2faf8ddbea7ac9e/lib/cotoha/error.rb) クラスで管理しており、HTTPレスポンスのステータスコードが 4xx ~ 5xx の場合には Exception を raise するようになっています。

Applications using `cotoha-ruby` are expected to handle exceptions properly.
> これは `cotoha-ruby` を使う側のアプリケーションで、適切に Exception をハンドリングしていただくことを期待しているためです。

```ruby
begin
  response = client.sentiment(sentence: text)
rescue Cotoha::Error => e
  puts e.message
end
```

I think this kind of structure is relatively common for API Clients. For example, [slack-ruby-client](https://github.com/slack-ruby/slack-ruby-client/blob/master/lib/slack/web/faraday/response/raise_error.rb) also raises its own Error class.
> API Client として、このような設計は比較的一般的かと思います。例えば [slack-ruby-client](https://github.com/slack-ruby/slack-ruby-client/blob/master/lib/slack/web/faraday/response/raise_error.rb) なども独自の Error クラスを raise するようになっています。

If the details of the error are insignificant (for example, in the log) in your application, you may want to review the handling of Exception in your application.
> ysato5654 さんのアプリケーションにおいて、エラーの詳細が重要ではない(例えばログに出力している程度)なのであれば、そのアプリケーションでの Exception のハンドリングを見直すと良いかもしれません。

If you have any trouble, you can mention @tanaken0515 in #newbie or #support in [ruby-jp slack](https://ruby-jp.github.io/). I've read your code "[ytvarb](https://github.com/ysato5654/ytvarb)", so I can help you.
> 何かお困りのことがあれば [ruby-jp slack](https://ruby-jp.github.io/) の #newbie や #support あたりで @tanaken0515 にメンションしてください。[ytvarb](https://github.com/ysato5654/ytvarb) のコードを読んだので、お手伝いできると思います。

**Comment by ysato5654** [comment]
ご回答頂きありがとうございます。（このまま日本語で回答させて頂きます。）

Exceptionでハンドリングする処理に対しては、問題ありません。

私の質問の意図としては、
Exceptionがraiseされたときも、sentimentメソッドの返り値の:result, :status, : messageにCOTOHAからの値が格納されていると
Exceptionのraise有無に関わらず、sentimentメソッドの返り値をそのままログに出力できるので、ytvarb側の実装が簡単になると考えていました。

只、
1) 完全にこちら側の都合である点
2) 現在は例外処理でExceptionを受け取って
本来sentimentメソッドの返り値となるハッシュ変数にエラー内容を自分で格納する実装にしております。（[cotohaha.rbの30行目以降](https://github.com/ysato5654/ytvarb/blob/master/lib/ytvarb/api/cotohaha.rb#L30)）

ですので、tanaken0515さんの意図が聞けただけで満足しております。
丁寧な回答ありがとうございました。
（またytvarbのコード読んで頂いたとのことで、ありがとうございます。）

**Comment by tanaken0515** [comment]
Thank you for your comment.
I made a pull request https://github.com/ysato5654/ytvarb/pull/2 because it seemed to make the `ytvarb` code look better. I hope you read it!
